name: bootstrap_icons
description: "A Flutter package for consuming Bootstrap icons API."
version: 1.0.0
homepage: https://github.com/regyfelipe/bootstrap_icons

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

author: Regy Robson
license: MIT
